server:
  port: 8600
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
    name: music-zuul

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/,http://${eureka.instance.hostname}:7002/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: zuul-8600
    prefer-ip-address: true
    hostname: www.music.com


zuul:
  #ignored-services: microservicecloud-dept
  #prefix: /music
  #ignored-services: "*"
  #配置服务名和路径名对应关系
  routes:
    consumer.serviceId: music-consumer
    consumer.path: /consumer/**
    adminManage.serviceId: music-adminManage
    adminManage.path: /admin/**
    dashBoard.serviceId: music-dashboard
    dashBoard.path: /dashboard/**
  servlet-path: /

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 600000
  threadpool:
    default:
      coreSize: 20


ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

